# Generated by Django 5.0.6 on 2024-07-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product_photos/')),
                ('status', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('shares', models.IntegerField(default=0)),
                ('traffic', models.IntegerField(default=0)),
                ('phone_no', models.CharField(max_length=15)),
                ('link', models.CharField(max_length=30)),
            ],
        ),
    ]
