# Generated by Django 5.0.6 on 2024-07-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_product_link_alter_product_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shares',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='traffic',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
